pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/dlgmlrnjs09/updowngg'
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    sh '''
                        npm install
                        npm run build
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('frontend') {
                    sh '''
                        sudo rm -rf /usr/share/nginx/html/*
                        sudo cp -r dist/* /usr/share/nginx/html/
                        sudo systemctl restart nginx
                    '''
                }
            }
        }
    }
}