pipeline {
    agent any

    tools {
        nodejs 'NodeJS'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/dlgmlrnjs09/updowngg'
            }
        }

        stage('Build') {
            steps {
                dir('frontend') {
                    sh '''
                        rm -rf node_modules
                        rm package-lock.json
                        npm install @rollup/rollup-linux-x64-gnu --save-optional
                        npm run build
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('frontend') {
                    sh '''
                        echo "Current directory:"
                        pwd
                        echo "Env file content:"
                        cat .env.production
                        rm -rf node_modules
                        rm package-lock.json
                        npm install @rollup/rollup-linux-x64-gnu --save-optional
                        npm run build
                    '''
                }
            }
        }
    }
}