pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/dlgmlrnjs09/updowngg'
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh '''
                        chmod +x ./gradlew
                        ./gradlew clean build
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('backend') {
                    sh '''
                        # 기존 프로세스 종료
                        pid=$(ps -ef | grep java | grep jar | awk '{print $2}')
                        if [ ! -z "$pid" ]; then
                            kill -9 $pid
                        fi

                        # JAR 파일 배포
                        nohup java -jar build/libs/backend-0.0.1-SNAPSHOT.jar &
                    '''
                }
            }
        }
    }
}