pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/dlgmlrnjs09/updowngg'
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh '''
                        export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64
                        export PATH=$JAVA_HOME/bin:$PATH

                        # Gradle 속성 설정
                        export GRADLE_OPTS="-Dorg.gradle.java.home=$JAVA_HOME -Dorg.gradle.daemon=false"

                        chmod +x ./gradlew
                        ./gradlew clean build --no-daemon --info
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('backend') {
                    sh '''
                        # 기존 프로세스 종료
                        pid=$(ps -ef | grep java | grep jar | awk '{print $2}')
                        if [ ! -z "$pid" ]; then
                            kill -9 $pid
                        fi

                        # JAR 파일 배포
                        nohup java -jar build/libs/backend-0.0.1-SNAPSHOT.jar &
                    '''
                }
            }
        }
    }
}