pipeline {
    agent any

    environment {
        JAVA_HOME = '/usr/lib/jvm/java-17-amazon-corretto.x86_64'
        PATH = "${JAVA_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/dlgmlrnjs09/updowngg'
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh '''
                        java -version
                        chmod +x ./gradlew
                        ./gradlew clean build -Dorg.gradle.java.home=${JAVA_HOME} --no-daemon --info
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('backend') {
                    sh '''
                        pid=$(ps -ef | grep java | grep jar | awk '{print $2}')
                        if [ ! -z "$pid" ]; then
                            kill -9 $pid
                        fi

                        nohup ${JAVA_HOME}/bin/java -jar build/libs/backend-0.0.1-SNAPSHOT.jar &
                    '''
                }
            }
        }
    }
}